# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0761e3548de4ebdae2246cbd03be4d6700d8f263b2911960a58322d74c4d342a35672ff501b8d3abe66e7ef492afb214174c0871c8b144fc3ffbbc000e1733

test:
  secret_key_base: 6776f3290752cd258e380405bab04e216108df0787f641fee1cb528355d539c66cd67554c534f5b564cb70d7cf3e6e2d4e7c6300cad58e1b6a7f11e3fa2f7092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
